### ISSUE TITLE
SSL error in dev mode with Node 17

### ISSUE THREAD

**Issue by conorao** [onflow/freshmint#26]
When creating a new freshmint project on linux with the latest version of Node.js provided in the system repositories (v. 17.8.0), the app fails to boot with a cryptography error.

```bash
$ NETWORK=testnet npm run dev

> freshmint-web@0.0.1 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/user/test-drop/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.digest (/home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:138906:21)
    at reduce (/home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:59527:49)
    at /home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:59451:21
    at done (/home/user/test-drop/node_modules/next/dist/compiled/neo-async/async.js:1:10308)
    at fromFile (/home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:59490:6)
    at /home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:59441:15
    at Array.<anonymous> (/home/user/test-drop/node_modules/next/dist/compiled/webpack/bundle5.js:140338:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.8.0
```

Downgrading to node 16 (LTS) or setting [this environment variable](https://stackoverflow.com/a/69746937) fixes this issue, but not sure if this should be outlined in the documentation.

**Comment by psiemens** [comment]
This error originates from Next.js and was also reported here: https://github.com/vercel/next.js/issues/30078

It's been fixed as of Next.js `12.0.3` (current version used by Freshmint is `12.0.1`). I've got a [PR to update the version](https://github.com/onflow/freshmint/pull/30), but if you've already generated your Next.js project, you'll need to manually upgrade `next`:

```sh
npm i next@latest
```
